name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Esto permite ejecutar la compilación manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permisos de ejecución a Gradlew
      run: chmod +x gradlew

    - name: Compilar APK (Debug)
      run: ./gradlew assembleDebug

    - name: Subir APK (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: TeraboxLinks-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
        retention-days: 7
